name: "Cachix"
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v15
        with:
          name: nvim
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - run: nix build .# -L
