name: Daily Flake Update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Install Nix with flakes support
        uses: DeterminateSystems/nix-installer-action@v9

      - name: Update flake
        run: nix flake update

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          
          # Only commit if there are changes
          if ! git diff --cached --quiet; then
            git commit -m "flake: Update lock file"
            git push
          else
            echo "No changes to commit"
          fi
      - name: Trigger Cachix workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: cachix.yaml
